/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.awt.Image;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Megamind
 */
public class TicTacToeGame extends javax.swing.JFrame {

    public char playerX;  //maximizing player
    public TicTacToeBoard myBoard;
    public char curPlayer;   //active player
    public char otherPlayer; //minimizing player
    public int robotMove;    //index to play that result in best score for robot
    /**
     * Creates new form TicTacToeGame
     */
    public TicTacToeGame(char c) {
        initComponents();
        playerX = c;   // this is either set to r if robot is to play first, or to h is human is to play first 
        myBoard = new TicTacToeBoard();
        curPlayer = playerX;
        
        //define who minimizing player is based on maximizing player
        if (c == 'r'){
            otherPlayer = 'h';
        }else{
            otherPlayer = 'r';
        }
        
        if (curPlayer == 'r'){
            robotMove();  //let robot make first move is he is maximizing player
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        myLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 175));
        setMinimumSize(new java.awt.Dimension(463, 445));
        setPreferredSize(new java.awt.Dimension(463, 440));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 30, 120, 100);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton2.setText("jButton1");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 20, 120, 100);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton3.setText("jButton1");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 30, 120, 100);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 150, 120, 100);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton5.setText("jButton1");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(170, 150, 120, 100);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton6.setText("jButton1");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(320, 150, 120, 100);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton7.setText("jButton1");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 280, 120, 100);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton8.setText("jButton1");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(170, 280, 120, 100);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/blank.png"))); // NOI18N
        jButton9.setText("jButton1");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(320, 280, 120, 100);

        myLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/grid1.png"))); // NOI18N
        myLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(myLabel);
        myLabel.setBounds(0, 0, 469, 413);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void declareWinner(){
        if (myBoard.hasWinner()){
            if((myBoard.getActivePlayer() == 'O') && playerX == 'r'){
                JOptionPane.showMessageDialog(null, "TickyBot wins");
            }
            else if ((myBoard.getActivePlayer() == 'X') && playerX == 'h'){
                JOptionPane.showMessageDialog(null, "TickyBot wins");
            }
            else if ((myBoard.getActivePlayer() == 'O') && playerX == 'h'){
                JOptionPane.showMessageDialog(null, "You win");  //this is never shown
            }
            else if ((myBoard.getActivePlayer() == 'X') && playerX == 'r'){
                JOptionPane.showMessageDialog(null, "You win"); //this is never shown
            }
        }
        else{
             JOptionPane.showMessageDialog(null, "Game ends with a draw");
        }
    }
    
    //method to modify images on buttons based on who active player is
    public void gamePlay(javax.swing.JButton b, int i){
        
         if (myBoard.isGridFree(i)){
            if (curPlayer == playerX){
                myBoard.makeMove(i,'X');
                ImageIcon icon = new ImageIcon("C://Users/Megamind/Documents/NetBeansProjects/TicTacToe/src/tictactoe/X.png");
                b.setIcon(icon);
                curPlayer = otherPlayer;
            }else{
                 myBoard.makeMove(i,'O');
                ImageIcon icon = new ImageIcon("C://Users/Megamind/Documents/NetBeansProjects/TicTacToe/src/tictactoe/o.png");
                b.setIcon(icon);
                curPlayer = playerX;
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid move");
        }
        
        if(myBoard.isGameOver()){
            declareWinner();
            this.setVisible(false);
        }
        
    }
    
    //a method to let the robot make determine and make its move. minimax is ran here
    public void robotMove(){
     
        Minimax ai = new Minimax();
        ai.minimax(0,myBoard);
        
                
           
        try{
                Thread.sleep(1500);
            } catch(InterruptedException ex){
                Thread.currentThread().interrupt();
            }
        robotMove = ai.getBestMove();

        switch (robotMove) {
            case 0:
                gamePlay(jButton1, robotMove);
                break;
            case 1:
                gamePlay(jButton2, robotMove);
                break;
            case 2:
                gamePlay(jButton3, robotMove);
                break;
            case 3:
                gamePlay(jButton4, robotMove);
                break;
            case 4:
                gamePlay(jButton5, robotMove);
                break;
            case 5:
                gamePlay(jButton6, robotMove);
                break;
            case 6:
                gamePlay(jButton7, robotMove);
                break;
            case 7:
                gamePlay(jButton8, robotMove);
                break;
            case 8:
                gamePlay(jButton9, robotMove);
                break;
            default:
                break;
        }   
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        gamePlay(jButton1, 0); 
        if (!myBoard.isGameOver() && curPlayer == 'r'){
            
            robotMove();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gamePlay(jButton2, 1); 
        if (!myBoard.isGameOver() && curPlayer == 'r'){
            
            robotMove();  //robot makes move after human
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        gamePlay(jButton3, 2); 
         if (!myBoard.isGameOver() && curPlayer == 'r'){
            robotMove();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        gamePlay(jButton4, 3); 
         if (!myBoard.isGameOver() && curPlayer == 'r'){
            robotMove();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        gamePlay(jButton5, 4); 
         if (!myBoard.isGameOver() && curPlayer == 'r'){
            robotMove();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        gamePlay(jButton6, 5); 
         if (!myBoard.isGameOver() && curPlayer == 'r'){
            robotMove();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        gamePlay(jButton7, 6); 
         if (!myBoard.isGameOver() && curPlayer == 'r'){
            robotMove();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here
        gamePlay(jButton8, 7); 
         if (!myBoard.isGameOver() && curPlayer == 'r'){
            robotMove();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        gamePlay(jButton9, 8); 
         if (!myBoard.isGameOver() && curPlayer == 'r'){
            robotMove();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeGame('r').setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel myLabel;
    // End of variables declaration//GEN-END:variables
}
